auto:        false
destination: _site
permalink:   pretty
pygments:    true
markdown:    maruku
permalink:   date
locale:      en
lsi:         true
url:         http://chkania.net
postimgurl:  http://chkania.net/img/posts
