auto:        false
destination: _site
permalink:   pretty
pygments:    true
markdown:    maruku
locale:      en
lsi:         true
url:         http://chkania.net
postimgurl:  http://chkania.net/img/posts
tag_page_layout: tag_page
tag_page_dir: tag
